"""Make document_filename nullable

Revision ID: 5eee5689d49b
Revises: c1155350b2ad
Create Date: 2025-07-14 12:14:55.237289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eee5689d49b'
down_revision = 'c1155350b2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('document_filename',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('document_filename',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
